evenfurther/pathfinding

src/bfs.rs
=> Minor doc fix: cost is not returned from bfs

Cargo.toml, README.md, src/edmondskarp.rs, src/lib.rs, tests/edmondskarp.rs
=> Implement Edmonds Karp

Cargo.toml, README.md, src/lib.rs
Compile ndarray only if really needed by the user. In other words: when the user want the edmondskarp algorithm.
=> Improve compilation time

src/kuhn_munkres.rs
This gives better performance.
=> Separate slack and slackx

src/astar.rs, src/edmonds_karp.rs, src/idastar.rs, tests/gps.rs, tests/kuhn_munkres.rs, tests/pathfinding.rs
Use rustfmt-nightly for reformatting
=> Reformatting

src/astar.rs, src/lib.rs, tests/pathfinding.rs
Also, rename InvCmpHolder into SmallestCostHolder and move it to
astar.rs.
=> Consider nodes closer to the target first

Cargo.toml, src/astar.rs, src/bfs.rs, src/fringe.rs, src/grid.rs, src/lib.rs
The crate and its types have been renamed, but are otherwise identical.
=> Update ordermap to indexmap

README.md, src/directed/mod.rs, src/directed/strongly_connected_components.rs, src/directed/topological_sort.rs, src/lib.rs, tests/strongly_connected_components.rs
=> Add strongly connected components implementation

src/directed/astar.rs
When prioritizing between equal estimated-cost nodes, seems it was incorrectly
using the parent node's cost so far. Instead, it's own cost so far should be
used.
Consider a simple graph:
A ----> B
\
--> C
Where A is the start node, and B and C have equal estimated cost, but different
cost so far. The "cost" value would previously be 0 for both B and C in the smallest cost
holder, thus not ensuring that the lowest cost-so-far node is picked for
expansion first.
=> Prioritize nodes using correct cost value in a*

README.md, benches/algos-fill.rs, benches/algos.rs, src/directed/iddfs.rs, src/directed/mod.rs, src/lib.rs, tests/pathfinding.rs
Done:
- Added `iddfs`
- Added docs based on `dfs` docs
- Adapted `idastar` doctests
- Added it to the `directed` module and its API to the library `prelude`.
Close #132 #134.
=> Base work on IDDFS

src/directed/bfs.rs, src/directed/topological_sort.rs, tests/pathfinding.rs
Fix #100 by providing examples in the documentation of `topological_sort`.
=> Add bfs_loop

src/directed/bfs.rs
Use a true BFS to find a BFS loop instead of going through all
successors of the starting node.
Close #207.
=> Reduce bfs_loop complexity

src/lib.rs
=> Add note on ordered-float crate

Cargo.toml
=> Upgrade to itertools 0.10

src/grid.rs, tests/grid.rs
- Add get() and get_mut() on Matrix
- Add reachable on Grid
=> grid reachable

src/kuhn_munkres.rs
=> Document possibility of looping endlessly in kuhn_munkres

benches/edmondskarp.rs, src/directed/edmonds_karp.rs, tests/codejam-2017-a.rs, tests/edmondskarp.rs
- Add minimum_cut capability to EdmondsKarp
- Add a new field to EdmondsKarp result with mincut
=> Add minimum cut capability to Edmonds Karp algorithm

src/grid.rs
- Add the possibility to dispay the grid with reversed line order
- Add Grid::from_coordinates()
=> grid from coordinates

.github/bors.toml, .github/workflows/tests.yml, Cargo.toml, README.md, tests/ui.rs
- Revert "Update codspeed-criterion-compat requirement from 1.1.0 to 2.1.0"
- Revert "Update MSRV to 1.70.0"
=> Restore MSRV to 1.65.0

benches/movingai.rs, examples/sliding-puzzle.rs, src/directed/edmonds_karp.rs, src/matrix.rs, tests/codejam-2017-a.rs, tests/dijkstra-all.rs, tests/edmondskarp.rs, tests/gps.rs, tests/kuhn_munkres.rs, tests/matrix.rs
- chore(tests): fix clippy warnings
- fix(matrix): better panic messages
- chore(tests/matrix): better matching of panic messages and errors
- fix(edmondskarp): better panic messages
- chore(tests/edmondskarp): better matching of panic messages
- chore(tests/kuhn_munkres): better matching of panic message
=> Clippy fixes in tests

src/directed/fringe.rs, src/directed/idastar.rs
This requires a MSRV bump to 1.70.0.
=> Use bool::is_some_and()

src/grid.rs, src/matrix.rs, src/utils.rs
- feat(utils): add `constrain()`
- feat(matrix): add `Matrix::constrain()`
- feat(grid): add `Grid::constrain()`
=> Add `constrain()` methods

src/matrix.rs, tests/matrix.rs
=> feat(matrix): add `Matrix::column_iter()`

README.md, src/lib.rs, tests/check-msrv-consistency.sh
=> fix(README): inline documentation to fix inner links to modules

tests/aoc-2023-17.rs
=> feat(tests): add new aoc-2023-17 test

tests/matrix.rs
- **test(matrix): test Matrix::indices()**
- **test(matrix): test Matrix::from_vec() with empty rows**
- **fix(tests): remove unnedded Matrix::as_ref() calls**
- **test(matrix): check against specific errors**
=> More tests

README.md
Introduced with commit: 279305d526c63bf99c7b05b629333601474f7298
=> fix(README): Broken link in the README.md

src/lib.rs, src/undirected/mod.rs, src/undirected/prim.rs, tests/prim.rs
=> feat(prim): add Prim's algorithm for finding MST

src/lib.rs, src/undirected/cliques.rs, src/undirected/mod.rs, tests/cliques.rs
to find maximal cliques in a graph.
=> Implement Bron-Kerbosch algorithm

benches/algos.rs, examples/bfs_bidirectional.rs, src/directed/bfs.rs, src/lib.rs, tests/pathfinding.rs
This PR implements a bidirectional BFS. I happened to implement this in a side project I was working on when I found that the `pathfinding` crate lacked this function. Since others may find it useful I wanted to offer adding it here as a contribution. 
I noticed that there is already an existing issue related to this - https://github.com/evenfurther/pathfinding/issues/543 - but didn't see any in-progress/open PRs.
=> Implement bidirectional BFS

Cargo.toml, examples/sliding-puzzle.rs, tests/connected-components.rs, tests/dijkstra-all.rs, tests/grid.rs, tests/topological_sort.rs
Also, use `ThreadRng` as standard rng.
=> chore(deps): update `rand` and `rand_xorshift` crates

src/directed/bfs.rs, src/lib.rs, src/noderefs.rs, tests/test_bfs_multiple_starts.rs
Changes to the BFS algorithms in response to https://github.com/evenfurther/pathfinding/issues/642
=> BFS multiple start nodes
