evenfurther/pathfinding

src/lib.rs

As this concern was exposed in this [SO question](https://stackoverflow.com/q/44876113/1233251), it is preferable that `num_traits` is re-exported from your crate, thus allowing users to use `num_traits` without having to add a compatible version on their own.

Export num_traits dependency as a public module

---

benches/bfs.rs

This adds a new 'corner-to-corner' benchmark for all algorithms, and adds the 'no-path' for all algorithms except `dfs`, which enters an infinite loop. I also reduced the map size from 128x128 to 64x64 to speed things up and avoid a stack-oveflow with `corner_to_corner_dfs`.

Added new benchmarks

---

Cargo.toml

ndarray 0.10.7 is necessary to be able to parse the trailing
comma in test sources.

Use stricter dependency on ndarray

---

src/astar.rs
tests/pathfinding.rs

This is a new attempt at an `astar_bag` function. It fixes the problems noted by the `astar_bag_path_multiple_ok` test. It does this by using a completely different internal structure: the easiest way I've found (and I tried a few!) seems to be to use `Rc`s to store the chain of a node and its parents. This also enables an interesting trade-off: if users are pathfinding over a complex node data-structure, this PR uses fewer `clones` of nodes than before, but at the expense of cloning `Rc`s. It entirely comes down to the relative cost of cloning `Rc` and `N` as to whether this is worth it or not... I've put one not-strictly-necessary instance of this in a separate commit, which can be removed if that's thought best.
Unfortunately I haven't been able to work out how to reuse this code in …

Attempt #3 at astar_bag

---

Cargo.toml
src/astar.rs
src/bfs.rs
src/fringe.rs
src/lib.rs

`OrderMap` is basically a `HashMap` that preserves insertion order.
That property isn't directly relevant to these algorithms, but it does
enable the very nice ability to do lookups directly by index, without
any hashing.
So in this commit, we now map to parents by their `usize` index, rather
than a whole clone of the node.  Many calls to `N::clone()` are avoided,
and hashing is only required for `insert`/`entry`, using `get_index` to
retrieve nodes the rest of the time.
The benefits are pretty good for the `algos` benchmark:
name                       master ns/iter  ordermap ns/iter  diff ns/iter   diff %  speedup
corner_to_corner_astar     44,816          24,973                 -19,843  -44.28%   x 1.79
corner_to_corner_bfs       690,052         547,510               -142,542  -20.66% …

Use ordermap in astar, bfs, and fringe

---

src/astar.rs
src/bfs.rs
src/connected_components.rs
src/dfs.rs
src/dijkstra.rs
src/fringe.rs
src/idastar.rs
src/lib.rs
src/topological_sort.rs
tests/connected-components.rs
tests/pathfinding.rs
tests/topological_sort.rs

If the pathfinding APIs accept `FnMut` closures, this gives the user more
flexibility, as their closures can mutate some of their captured state.
`FnMut` is a supertrait of `Fn`, so existing use cases are not affected by
this change.
The effect internally is that such closures can't be shared in multiple
places simultaneously, since calling an `FnMut` requires exclusive access.
None of the current implementations have a problem with this; they just
needed to update to mutable bindings.  (That's an internal detail, not an
API change.)
A few tests were using counters in `RefCell` or `RwLock`, and those can now
be mutated directly, captured in `FnMut` closures.

Accept FnMut closures, instead of just Fn

---

src/matrix.rs

This allows the removal of `to_vec` which now comes as part of the slice
`Deref` operation.

Implement Deref/DerefMut instead of AsRef/AsMut

---

Cargo.toml

It looks like the problems with criterion might be due to a transient
nightly rust issue.
Fix #219

Reinstate criterion

---

Cargo.toml

The `criterion` crate does not check that it can be configured with
`cargo -Z minimal-version` and thus indicates incorrect
(as in "not strict enough") dependencies in its `Cargo.toml`.
By forcing the use of a later version of `rayon`
(which is used by `criterion`), we prevent dragging in a
non-compiling version of `crossbeam-utils`.

Add a dummy dependency to fix a "cargo -Z minimal-version" problem

---

README.md

Thanks to bors, it always builds (or it is not merged).

Remove building badge

---

Cargo.toml
src/directed/astar.rs
src/directed/bfs.rs
src/directed/dijkstra.rs
src/directed/fringe.rs
src/directed/mod.rs

IndexMap's default hasher is cryptographically-secure, which is completely unnecessary for pathfinding. Using the fxhash hasher, I get around 10%-55% improvements where bigger maps have better performance.
All tests pass(except the codejam tests, but they fail without the change as well), and all benchmarks are either faster or unchanged.

Use faster rustc-hash hasher for IndexMap

---

src/directed/yen.rs
tests/yen.rs

This PR fixes an issue in the implementation of Yen's algorithm that causes a panic if an alternative path is more than two steps longer than a previous found path.

yen: fix range index out of range panic

---

src/directed/edmonds_karp.rs
src/kuhn_munkres.rs
src/matrix.rs
tests/dijkstra-all.rs
tests/matrix.rs

This looks more natural this way:
matrix[(1, 2)]
instead of
matrix[&(1, 2)]
This is a semver incompatible change which requires bumping the
major version.

Use tuples instead of tuples ref for matrix index

---

src/matrix.rs
tests/matrix.rs

The `Vec<C>` and `Vec<MaybeUninit<C>>` don't have any long-term
guarantee of having the same in-memory representation.

Remove unused uninit/assume_init on Matrix

---

src/directed/bfs.rs
src/directed/mod.rs

It's my understanding that bfs always goes through nodes in the order they are found. I added a `dbg!(i)` to the loop and saw it was always consecutive. This makes me believe that the VecDeque is unnecessary here.
For some reason however, this adds a 40% regression to the benchmarks in this crate. I'm investigating why that might be the case, since as far as I've been able to test, this change makes no algorithmic behavior changes

remove vecdeque from bfs

---

src/matrix.rs

My first try using `pathfinding` took longer than expected because I assumed coordinates were in `(x, y)` order, not `(y, x)` aka `(row, col)` order. It's clear after reading a bit more of the documentation and code, but I thought it might be beneficial to make it explicit in the docs.

Clarify ordering of coordinate tuples

---

src/matrix.rs
tests/matrix.rs

I wanted to find a good way to find coordinates in the Matrix with specific values.
My initial approach was something like this:
```rust
let idx = m
.values()
.enumerate()
.find(|(_, &v| v == needle)
.unwrap()
.0;
let pos = (idx / m.columns, idx % m.columns);
```
Then I realized I could simplify to this:
```rust
let pos = m
.indices()
.zip(g.values())
.find(|(_, &v)| v == needle)
.unwrap()
.0;
```
If this is a common pattern, then this could be simplified further to
```rust
let pos = m
.items()
.find(|&(_, v)| v == &needle)
.unwrap()
.0;
```
Maybe this could be a standard API?

Implement Matrix::items()

---

src/directed/edmonds_karp.rs
tests/edmondskarp.rs

The cancel_flow method searches for a path between "from" to the source (and one from "to" to the sink) but then cancels the maximum amount of flow among all edges of this path, instead of the minimum amount of flow among all edges. This can cause negative residual capacities and hence also negative flows. This pull request adds a corresponding test and replaces the max operator with the min operator to fix the bug in the cancel_flow method.

Fix cancel_flow

---

src/matrix.rs
tests/matrix.rs

I ended up wanting to create a Matrix this way the very first time I used `pathfinding`, so here's the code for it in case you think it would make sense to add back to the library. It doesn't add any fundamentally new capabilities, but it seems like a pretty natural convenience to have. It's a small enough change that I figured it would hopefully be okay to skip creating an issue first.

Allow creating a Matrix based on a function from position to value

---

src/directed/edmonds_karp.rs
src/directed/topological_sort.rs

- Do not use `bool::then()` in `filter_map()`
- Use `or_default()` rather than `or_insert_with()` with default value

Style updates

---

src/directed/yen.rs
tests/yen.rs

Fix #467
Bug reported and fix provided by Felix Schaefer <dev@felix-schaefer.de>

fix(yen): return all loopless paths

---

src/matrix.rs
tests/matrix.rs

This allows using `matrix.iter().rev()` to handle rows in reverse order.

feat(matrix): implement DoubleEndedIterator for RowIterator

---

src/directed/dfs.rs
tests/dfs-reach.rs

fix(dfs_reach): visit nodes in the documented order

---

Cargo.toml
benches/matrices.rs

Putting this in as a pre-requisite to https://github.com/evenfurther/pathfinding/pull/524.
Would like to get a baseline for square matrix transposes before adding support for non-square matrices.

feat(bench): add bench for matrix transposition

---

Cargo.toml

They added a [lint_groups_priority](https://github.com/rust-lang/rust-clippy/pull/11832) check last week that caused [this failure in CI](https://github.com/evenfurther/pathfinding/actions/runs/7853251283/job/21432650495#step:5:170).
```
error: lint group `pedantic` has the same priority (0) as a lint
--> Cargo.toml:53:1
|
53 | pedantic = "deny"
| ^^^^^^^^   ------ has an implicit priority of 0
54 | module_name_repetitions = "allow"
| ----------------------- has the same priority as this lint
|
= note: the order of the lints in the table is ignored by Cargo
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#lint_groups_priority
= note: `#[deny(clippy::lint_groups_priority)]` on by default
help: to have lints override the group set `pedantic` to …
```

fix(deps): add priority to clippy lints for lint_groups_priority

---

Cargo.toml
benches/matrices.rs
src/matrix.rs
tests/matrix.rs

Close https://github.com/evenfurther/pathfinding/issues/497.
I took a stab at the most basic implementation described in https://en.wikipedia.org/wiki/In-place_matrix_transposition. There are definitely more optimal approaches given the references from that page, as this requires MN additional memory for recording visited locations.
Given the added complexity and memory, would it be preferable to fork the logic here for square vs non-square matrices?

feat(matrix): add in-place matrix transposition for non-square matrix

---

Cargo.toml
src/matrix.rs

Hand-coding the bit vector gives better performances than using the bitvec
crate. It is used in two places only which makes it easy to read.

feat(matrix): do not use bitvec crate for simple operations

---

Cargo.toml
src/kuhn_munkres.rs

This makes Kuhn-Munkres run faster.

feat: replace `FixedBitSet` by `IndexSet` for performance reasons

---

tests/matrix.rs

- **test(matrix): more complete test for Matrix::flip_ud()**
- **test(matrix): more complete test for Matrix::transpose_in_place_non_square()**

Add more tests

---

Cargo.toml

This is necessary until the lint gets fixed to not handle hyperlinks as pure text and count towards the characters limit.

chore(Cargo.toml): allow `clippy::too_long_first_doc_paragraph`

---

Cargo.toml
src/lib.rs

This release of Rust includes a fix for CVE-2024-24576. It also allows a more recent of codspeed-criterion-compat to be used for measuring performance gains and losses.

fix!(msrv): update MSRV to 1.77.2

---

src/undirected/kruskal.rs

The temporary wouldn't live long enough otherwise, and this code would be rejected by Rust 2024.

fix(kruskal): accept owned data into the method

---

.github/workflows/tests.yml
Cargo.toml
benches/matrices.rs
benches/movingai.rs
examples/sliding-puzzle.rs
src/directed/astar.rs
src/directed/dijkstra.rs
src/directed/fringe.rs
src/directed/mod.rs
src/directed/strongly_connected_components.rs
src/directed/topological_sort.rs
src/lib.rs
src/undirected/connected_components.rs
src/undirected/kruskal.rs
src/utils.rs
tests/codejam-2017-a.rs
tests/edmondskarp.rs
tests/gps.rs
tests/matrix.rs
tests/pathfinding.rs
tests/strongly_connected_components.rs
tests/topological_sort.rs

Requires MSRV to be bumped to 1.81.0.

fix: use `expect` attributes instead of `allow`

---

src/matrix.rs
tests/matrix.rs

This comes in addition to `(usize, usize)`.

feat: accept `&(usize, usize)` as `Matrix` index

---

src/directed/dijkstra.rs

This backs out comit 808b951c5a9eb5dd25adbd46a5887525d0a0913d "Remove optimization which gives worst benchmark results", as it severely degrades performances as shown in
<https://github.com/evenfurther/pathfinding/issues/639>.

fix(perf): back out commit 808b951c5a9eb5dd25adbd46a5887525d0a0913d

---

src/directed/dijkstra.rs
tests/dijkstra-reach.rs

The `dijkstra_reach` function used a successors function which not only took the node whose successors are seeked, but also the cost so far to reach this node. This is an oversight, as this information can be retrieved from the iterator returned by `dijkstra_reach`.
The user is free to stop iterating if a maximum cost is reached, so there is no loss in functionality.
Fix #647

fix(dijkstra)!: remove unneeded partial cost parameter
